### ISSUE TITLE
Implement move_file, copy_file to destination gdrive folder

### ISSUE THREAD

**Issue by mahiki** [glotlabs/gdrive#10]
My automation with google docs requires building documents and then copying or moving them to a share folder location.

My understanding is that the move process is an implementation of replacing an objects parent id, this is supported by the g drive API.

I believe most of this list is already being implemented, for completeness here are the gdrive file operations that I think are basic file system functionality:
```
create new folder
create new file (maybe this is not gdrive but gdocs, gsheets etc)
move file/folder to new destination
copy file/folder to new destination
rename file/folder
download file
upload file to specific folder
manage sharing permissions of folder/file
```

**Comment by Xpistos** [comment]
I would also like to see the ability to upload as google sheets or google docs. I have csv's and xls' files I would like to be upload as native google sheets without my direct intervention to convert them.

**Comment by prasmussen** [comment]
Everything mentioned (except creating new files) is implemented in the latest release.
