### ISSUE TITLE
Download shared folders

### ISSUE THREAD

**Issue by Nik3939** [glotlabs/gdrive#100]
Hi! Is there a way to download a folder present in the "shared with me" of my Google Drive? I can visualize files present there with the command "gdrive files list --drive [ID]" but I didn't find a way to download them. Thank you!

**Comment by manestay** [comment]
I figured it out, once you find the [ID] of the file (or directory) you want to download from the shared drive, you can just use it directly `gdrive files download [ID]`. No need to specify `--drive` for this command.

**Comment by Nik3939** [comment]
Thank you @manestay ! I tried it and it works.
