### ISSUE TITLE
Upload to Specific Gdrive Folder

### ISSUE THREAD

**Issue by TheLoneArranger** [glotlabs/gdrive#105]
I'm new to Gdrive. I have not been able to locate a user manual. I need to upload a file into a specific Gdrive folder.
I have used "gdrive files upload myFile" but this puts myFile into my root Gdrive folder.
"gdrive --help" doesn't appear to have the answer.
What am I missing?

**Comment by marcelog09** [comment]
I have the same doubt

#Edit

I discovered that you just need to add the --parent parameter to the command followed by the folder id (https://ploi.io/documentation/database/where-do-i-get-google-drive-folder-id). Exemple:

gdrive files upload --parent [FOLDER_ID] [FILE_PATH]
