### ISSUE TITLE
Did 3.9.1 get re-tagged?

### ISSUE THREAD

**Issue by chenrui333** [glotlabs/gdrive#107]
👋 While [upgrading rust to 1.76.0](https://github.com/Homebrew/homebrew-core/pull/162122), we found that [gdrive 3.9.1 source tarball has checksum mismatch](https://github.com/Homebrew/homebrew-core/pull/162481), raise this issue to confirm if there was a git re-tagging happened. Thanks! 🙏

**Comment by prasmussen** [comment]
Correct, I was fighting with the CI so it got retagged a couple of times.
