### ISSUE TITLE
working with mkdir

### ISSUE THREAD

**Issue by philfried** [glotlabs/gdrive#11]
In my batch I'd need to create a folder, in the example below I call it TEMPFOLDER,
this is were I want to upload the files to. I solved it this way:

```
gdrive files mkdir --parent 1M7gb7QACMgDsQc7mSrgE8jAQTgt4RorS TEMPFOLDER > c:/tempReply.txt 2>&1
set /p VARFOLDER=<c:/tempReply.txt
set gFolderID=%VARFOLDER:~-33%
```
I read out the message the gdrive.exe-command sends, and extract the ID of the newly
created folder and save it in a variable for further use in my script.

Is there an easier way of "grabbing" the ID of the generated Folder?
Like the **gdrive files mkdir ...** command only replys the ID?
thanks!
philip

**Comment by prasmussen** [comment]
I'm not a windows user but it seems like you can use powershell to more easily extract the id. Something like:
```
(echo "Created directory 'test' with id: 11h0OFki84QhHKZrJHRNIdfKa4YkG8zMp").Split(": ")[1]
```

Anyway, I agree that it can be useful to have a flag which prints some minimal output, so in version 3.4.0 you can now use the `--print-only-id` flag
