### ISSUE TITLE
Unable to list shared drives files, I tried creating a shortcut but couldn't download the file as we..

### ISSUE THREAD

**Issue by tbharghav** [glotlabs/gdrive#13]
[root@oc120123232 gdriveold]# gdrive files list
Id                                  Name                                        Type       Size      Created
1-iCkAr8v9q-1RUwdUUoufE3p4cAL8gh_   GDToT                                       folder               2021-07-16 01:32:34
1GI6vhMgz4nN3Yz7M3RjvB0jjz-UQcObj   Tom.Clancys.Jack.Rya…HD.7.1.Atmos-FGT.zip   document             2023-01-27 06:05:36
[root@oc120123232 gdriveold]#
[root@oc120123232 gdriveold]#
[root@oc120123232 gdriveold]#
[root@oc120123232 gdriveold]# gdrive files download 1GI6vhMgz4nN3Yz7M3RjvB0jjz-UQcObj
Error: Failed to download file: Bad Request: {"error":{"code":403,"errors":[{"domain":"global","location":"alt","locationType":"parameter","message":"Only files with binary content can be downloaded. Use Export with Docs Editors files.","reason":"fileNotDownloadable"}],"message":"Only files with binary content can be downloaded. Use Export with Docs Editors files."}}

[root@oc120123232 gdriveold]# gdrive files  export 1GI6vhMgz4nN3Yz7M3RjvB0jjz-UQcObj mkv
Error: Mime type on drive file 'application/vnd.google-apps.shortcut' is not supported
[root@oc120123232 gdriveold]#

**Comment by prasmussen** [comment]
[v3.8.0](https://github.com/glotlabs/gdrive/releases/tag/3.8.0) has better support for shared drives.
Try `… download --follow-shortcuts …` for example
