### ISSUE TITLE
 Needs verification

### ISSUE THREAD

**Issue by Stevemoretz** [glotlabs/gdrive#17]
Is this normal or did I do something wrong?
<img width="527" alt="Screen Shot 1401-11-14 at 13 15 06" src="https://user-images.githubusercontent.com/27680142/216567522-fc87ff27-c254-4189-acf4-07614edb6b89.png">

**Comment by prasmussen** [comment]
This is normal. As far as I know it will continue to work without verification. You can send it in for verification to avoid this warning, but it is a complicated procedure.

**Comment by Stevemoretz** [comment]
Well that's fine I thought it stops working after 7 days sounds great thanks :)

**Comment by prasmussen** [comment]
The refresh token will expire after 7 days if your consent screen is in testing mode, so make sure you have set it in production mode (I just recently discovered this and added it to the docs)
![image](https://user-images.githubusercontent.com/720405/216594895-af0b2acf-b3fc-41e0-99c7-207229cdfe47.png)

**Comment by Stevemoretz** [comment]
> The refresh token will expire after 7 days if your consent screen is in testing mode, so make sure you have set it in production mode (I just recently discovered this and added it to the docs) ![image](https://user-images.githubusercontent.com/720405/216594895-af0b2acf-b3fc-41e0-99c7-207229cdfe47.png)

Thank you for this I followed the docs and it says in production for me too all good :)
Maybe just add to the docs that `Needs verification` doesn't matter at all
