### ISSUE TITLE
Upload directory creates a new one instead of overriding

### ISSUE THREAD

**Issue by Stevemoretz** [glotlabs/gdrive#18]
Every time I upload a directory it creates a new one.

```bash
gdrive files upload /root/scripts/logs --parent="1a-MfzmswoEskojkR8lAvuygwApeU6ft4" --recursive
```

<img width="728" alt="Screen Shot 1401-11-14 at 13 26 33" src="https://user-images.githubusercontent.com/27680142/216570133-1a16013d-7c4d-450d-8223-0b1a6d9dff8c.png">

Can't even use the update to do this:

```bash
gdrive files update "1a-MfzmswoEskojkR8lAvuygwApeU5ft4" /root/scripts/logs
Updating 1a-MfzmswoEskojkR8lAvuygwApeU5ft4 with /root/scripts/logs
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 21, kind: IsADirectory, message: "Is a directory" }', /root/.cargo/git/checkouts/google-apis-rs-9de08c63e04c0b9f/1f75444/google-apis-common/src/lib.rs:687:56
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by prasmussen** [comment]
This is expected behaviour and is also stated in the help message (`gdrive files upload --help`).
`update` only works on files, I will add a note to my list to show a proper error message when trying to update a folder.
