### ISSUE TITLE
Every Week Gdrive requires permisssion

### ISSUE THREAD

**Issue by Xpistos** [glotlabs/gdrive#22]
Why do I keep getting this request and how to I get it to stop???

```
Gdrive requires permissions to manage your files on Google Drive.
Open the url in your browser and follow the instructions:

```

**Comment by prasmussen** [comment]
Make sure your consent screen is in production status. See the 3 last steps [here](https://github.com/glotlabs/gdrive/blob/main/docs/create_google_api_credentials.md).

It should look like this:
![image](https://user-images.githubusercontent.com/720405/219772251-b0baec93-7bc9-46a3-99a7-8037ee57e0da.png)

**Comment by Xpistos** [comment]
Not sure how I missed that but it is now set.  I will see how it works next
per my script next Wednesday and let you know. Thanks!!!

**Comment by prasmussen** [comment]
You also need to refresh your token one more time after setting it to production.

(You probably didn't miss the steps btw, they were added not long ago when it was discovered that in testing mode the refresh token only last for 7 days.)

**Comment by jordymeow** [comment]
You didn't need to get through the [verification](https://support.google.com/cloud/answer/9110914)? Seems like every time we publish an app, we need to get through it.
