### ISSUE TITLE
`files list` replacing part of long file names with '...'

### ISSUE THREAD

**Issue by tvidal-net** [glotlabs/gdrive#27]
I am trying to create a script to download missing files from the local storage. It uses the file names to check if they exist locally, but I noticed some files were always downloading regardless of existing or not.

I was checking the results of `gdrive files list` and noticed long file names get truncated with the middle part replaced by `...` which causes the file name to be different than what is stored in google drive.

I have a few questions/suggestions:
1. Would it be possible to add a flag to enable/disable this long name truncation?
2. Would it be possible to add flags to show/hide the header, change the column/field separator to make the output easier to parse?
3. Would it be possible to have the recursive download overwrite only local files if they are more recent? This would actually make the whole local sync issue much more manageable.

Thank you for your great contrib to the community, I am not proficient in go, but would you mind if I sent a PR with a suggestion implementation of the above features?

**Comment by prasmussen** [comment]
1. Yes
2. Yes, Yes
3. I think md5 sums should be compared to decide if the files are equal

I might take a look at these tomorrow, if not feel free to create a PR

**Comment by prasmussen** [comment]
These are all implemented in [3.7.0](https://github.com/glotlabs/gdrive/releases/tag/3.7.0). The release notes has more details.
Thanks for the suggestions!
