### ISSUE TITLE
Why rewrite from Go to Rust?

### ISSUE THREAD

**Issue by SmartBoy84** [glotlabs/gdrive#29]
What was the reasoning for rewriting the application in rust? Did you encounter any limitations in Go?

**Comment by prasmussen** [comment]
The short answer is that I want more experience with Rust.
I'm using my spare time to work on this and what I get back is experience.

There is no limitations in Go that prevents me from using it for this project, but Rust have some language features that I enjoy using (that are missing from most mainstream languages):
- Tagged unions
- Null safety
- Immutable data (by default)
- More type safe in general
