### ISSUE TITLE
Document export not working

### ISSUE THREAD

**Issue by ControlFreakyKiwi** [glotlabs/gdrive#3]
Thanks very much for your work on these projects, I have been using the previous gdrive for sometime and have found it great until a HDD crash and unable to access it again so thought I would try GDrive3.

previously I was able to download a Excel *xlsx file, Is this not possible now ? looking at the error 

Bad Request: {"error":{"code":403,"errors":[{"domain":"global","location":"alt","locationType":"parameter","message":"Only files with binary content can be downloaded. Use Export with Docs Editors files.","reason":"fileNotDownloadable"}],"message":"Only files with binary content can be downloaded. Use Export with Docs Editors files."}}

**Comment by prasmussen** [comment]
I guess you were using the export command for that before? This is not implemented yet in gdrive3.

**Comment by ControlFreakyKiwi** [comment]
Yes, I was , I managed to get it going by finally understanding how to implement the [Bugcode](https://github.com/BugCode1/gdrive) tip but look forward to using gdrive3 in the future, thanks in advance

**Comment by prasmussen** [comment]
`gdrive files export` is now possible in v3.4.0
