### ISSUE TITLE
Failed to update spreadsheet with csv file

### ISSUE THREAD

**Issue by HeadLessHUN** [glotlabs/gdrive#31]
is there a way to use Resumable uploads described here https://developers.google.com/drive/api/guides/manage-uploads?
 
```
 
Updating dfbgfbdfbdfb with dfbvgdfvd.csv
Error: Failed to update file: Http status indicates failure: Response { status: 413, version: HTTP/2.0, headers: {"x-guploader-uploadid": "fvgdvdsvdvdvdvd", "access-control-allow-credentials": "true", "cache-control": "private, max-age=0", "content-type": "application/json; charset=UTF-8", "date": "Mon, 20 Mar 2023 09:24:32 GMT", "expires": "Mon, 20 Mar 2023 09:24:32 GMT", "server": "ESF", "vary": "Origin, X-Origin", "x-content-type-options": "nosniff", "x-frame-options": "SAMEORIGIN", "x-xss-protection": "0", "content-length": "215", "alt-svc": "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000"}, body: Body(Full(b"{\n  \"error\": {\n    \"code\": 413,\n    \"message\": \"Request Too Large\",\n    \"errors\": [\n      {\n        \"message\": \"Request Too Large\",\n        \"domain\": \"global\",\n        \"reason\": \"uploadTooLarge\"\n      }\n    ]\n  }\n}\n")) }
```

**Comment by prasmussen** [comment]
Resumable uploads are used for files that are larger then the selected chunk size (~32MB per default).

How large is you file?
Are you trying to update a google document?

**Comment by HeadLessHUN** [comment]
hello, the largest file i'm trying to update  is around 220mb. And yes it is a google sheet file. I can upload it as normal file not google doc.

**Comment by prasmussen** [comment]
`files import` does not support update yet, but it seems like this works for updating spreadsheets:
```
gdrive files update --mime application/vnd.google-apps.spreadsheet <file_id> <path_to_file>
```

**Comment by HeadLessHUN** [comment]
Well it is working without mime type, but large files still does not works.

**Comment by prasmussen** [comment]
Aha, then my guess would be that you are hitting some limitation in the api: https://support.google.com/drive/answer/37603?hl=en

Are you able to convert the same csv when uploading through the drive ui?

**Comment by HeadLessHUN** [comment]
Well you might be onto something, I'll close it here, I'm pretty sure that it hits one of these limits...
