### ISSUE TITLE
Progress bar during download or upload

### ISSUE THREAD

**Issue by JinZhangYu** [glotlabs/gdrive#44]
Current download or upload will only show one line here,
`Downloading xxxx.file`

Whether it is possible to add a progress bar like `tqdm` to show the speed and estimated finish time?

**Comment by hubb3r** [comment]
I endorse the idea

**Comment by hirotong** [comment]
🙌

**Comment by DLandDS** [comment]
up

**Comment by gomteshhatgine** [comment]
It would be helpful to have a progress bar when uploading files using the `gdrive` tool. This feature would enhance the user experience by providing real-time feedback on the upload status, especially for larger files.

**Comment by maxall41** [comment]
bump

**Comment by JinZhangYu** [comment]
I did not use this tool anymore. I switch to gdown https://github.com/wkentaro/gdown.
A better one with progress bars. 
Also, I can directly download files just using `id`, and I do not even need to save them to my google drive anymore.
