### ISSUE TITLE
Command 'gdrive' not found

### ISSUE THREAD

**Issue by jincan333** [glotlabs/gdrive#47]
after I move gdrive to usr/local/bin, when I enter "gdrive account add", it gets this:
`Command 'gdrive' not found, did you mean:
  command 'drive' from snap drive (current)
See 'snap info <snapname>' for additional versions.`
can anyone help solve the problem?

**Comment by jincan333** [comment]
> 

Thank you! /usr/local/bin is in my PATH. But it's not a directory in my system! So I move gdrive to the home directory and add home directory to my PATH. After this, I can run `gdrive account add` successfully!

**Comment by Glich440** [comment]
it is really not recommended to add your home path to the PATH (mainly due to security concerns but it can also introduce some issues) I would recomend you either create /usr/local/bin and use that directory or add a bin folder such as ~/bin or ~/.local/bin

**Comment by jincan333** [comment]
ok, thank you! Actually, I create a personal fold in home and put it there. But I found a new problem, I can't give approval to gdrive after I run `gdrive account add` and input my ID and secret. It prompts `127.0.0.1 refused to connect.` I tried some methods to the problem by google, but It all didn't work.

**Comment by Glich440** [comment]
are you currently running a web server on that machine?
and by saying it prompts that do you mean the browser o gdrive?

**Comment by jincan333** [comment]
Yes, I can surf the internet normally but I can't follow the URL after I enter my ID.
It's the browser.

**Comment by Glich440** [comment]
have you tried another browser?

**Comment by Glich440** [comment]
if that still doesn't work I would suggest you close this issue and open a new one or at least change the title

**Comment by jincan333** [comment]
Yes, I tried chrome and edge, neither did they work.
