### ISSUE TITLE
-p upload file to directory not working

### ISSUE THREAD

**Issue by smack893** [glotlabs/gdrive#5]
first of thank you so much to continue this project i am using your project from last 1 year and i am facing this issue with this version previously i am using your v2 version and and i use -P directoryId before file path so it upload file to that specific directory but its not working with this version 
error: Found argument '-p' which wasn't expected, or isn't valid in this context

  If you tried to supply '-p' as a value rather than a flag, use '-- -p'

**Comment by prasmussen** [comment]
You can use `gdrive files upload --help` to see all the available options.
`--parent` should work the same as `-p` in the previous version
