### ISSUE TITLE
Failed to upload file: Token retrieval failed

### ISSUE THREAD

**Issue by DifficultPhil** [glotlabs/gdrive#51]
gdrive worked 6 day, and now i have error
`Error: Failed to upload file: Token retrieval failed: error creating server listener: Address in use (os error 98)`

how fix this?

**Comment by Baldoma** [comment]
did you solve this problem?

**Comment by DifficultPhil** [comment]
Yes, the tokens for gdrive disappeared on my server, I generated them from my PC, placed them on the server and everything worked again
