### ISSUE TITLE
Error: Failed to upload file: The media size 9223372036854775807 exceeds the maximum allowed upload size of 5497558138880

### ISSUE THREAD

**Issue by youonlytrackonce** [glotlabs/gdrive#9]
Hello,
thank you very much for your great work!!

I get the error message stated in the title. Where can I increase this limit?

Thank you!

**Comment by prasmussen** [comment]
The google drive api doesn't allow you to upload files bigger than 5TB as far as I know.

**Comment by fesimsekasel** [comment]
Thank you for the clarification!

**Comment by youonlytrackonce** [comment]
Thank you for the clarification!!
